apiVersion: apps/v1
kind: Deployment
metadata:
  name: gochat-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gochat-api
  template:
    metadata:
      labels:
        app: gochat-api
    spec:
      containers:
        - name: gochat-api
          image: eddygarr/gochat-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_NAME
              value: gochat-edgarbagagem
            - name: DB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: DB_TOKEN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: JWT_SECRET
            - name: FRONTEND_URL
              value: http://gochat-frontend-service
