apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  DB_TOKEN: #Replace by your DB_TOKEN / echo -n "your DB_TOKEN" | base64
  JWT_SECRET: #Replace by your JWT_SECRET / echo -n "your JWT_SECRET" | base64