apiVersion: v1
kind: Service
metadata:
  name: gochat-ws-service
  namespace: default
spec:
  selector:
    app: gochat-ws
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
