apiVersion: batch/v1
kind: CronJob
metadata:
  name: joke-cronjob
  namespace: default
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: joke-cronjob
              image: eddygarr/joke-cronjob:latest
              env:
                - name: WEBSOCKET_SERVER
                  value: "http://gochat-ws-service:3000"
          restartPolicy: OnFailure
